language: node_js
node_js:
  - node

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - yarn bootstrap

script:
  - yarn test
  - yarn build

deploy:
  provider: script
  script: yarn deploy
  skip_cleanup: true
  on:
    branch: master
