language: node_js
node_js:
  - node

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn bootstrap
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: packages/pomodoro-web/build
  on:
    branch: master
